cerita_billy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='index')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/',  include('story3.urls', namespace='story3')),
    path('story5/',  include('story5.urls', namespace='story5')),
    path('story6/',  include('story6.urls', namespace='story6')),
    path('story7/',  include('story7.urls', namespace='story7')),
    path('story8/',  include('story8.urls', namespace='story8')),
    path('story9/',  include('story9.urls', namespace='story9')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

story5/urls.py
from django.urls import path
from . import views

# Create your views here.


app_name = 'story5'

urlpatterns = [
    path('', views.story5, name='story5'),
    path('<int:id>/', views.detail_matkul, name='detail'),
]

story5/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime

# Create your models here.


class Jadwal(models.Model):
    nama_matkul = models.CharField(max_length=50)
    nama_dosen = models.CharField(max_length=50)
    kelas = models.CharField(max_length=3, default="")
    semester_berapa = models.IntegerField(default=3)
    deskripsi = models.TextField(default="")

    def __str__(self):
        return self.nama_matkul

story5/forms.py
from django import forms
from django.db.models import fields
from .models import Jadwal

# Create your models here.


class JadwalForm(forms.ModelForm):
    class Meta():
        model = Jadwal
        fields = "__all__"
        widgets = {
            'nama_matkul' : forms.TextInput(attrs={'placeholder' : 'PPW'}),
            'nama_dosen' : forms.TextInput(attrs={'placeholder' : 'Iis'}),
            'kelas' : forms.TextInput(attrs={'placeholder' : 'C'}),
            'semester_berapa' : forms.TextInput(attrs={'placeholder' : '3'}),
            'deskripsi' : forms.Textarea(attrs={'placeholder' : 'omoshiroi'}),
        }
        labels = {
            'nama_matkul' : "Nama Mata Kuliah",
            'nama_dosen' : "Nama Dosen",
            'kelas' : "Kelas",
            'semester_berapa' : "Semester",
            'deskripsi' : "Deskripsi",
        }

story5/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, request, response
from .models import Jadwal
from .forms import JadwalForm



def story5(request):
    form = JadwalForm(request.POST or None)
    jadwal = Jadwal.objects.all()
    if form.is_valid():
        form.save()
        return redirect('/story5/')
    response = {
        'form': form,
        'jadwal': jadwal,
    }
    return render(request, 'story5/story5.html', response)


def detail_matkul(request, id):
    matkul = Jadwal.objects.get(id=id)
    response = {
        'matkul': matkul
    }
    return render(request, 'story5/matkul.html', response)

story5/templates/story5/matkul.html
{% extends 'base.html' %}
<!-- Block of Style-->
{% block style %}
<!-- Apabila dibutuhkan Style internal dapat diissi disini-->
{% endblock style %}
<!--Block of title-->
{% block title %}Mata Kuliah{% endblock title %}
<!-- Start of Content -->
{% load crispy_forms_tags %}
{% block content %}
{% load crispy_forms_tags %}
<table>
  <tr>
    <td>Nama Mata Kuliah</td>
    <td>{{ matkul.nama_matkul }}</td>
  </tr>
  <tr>
    <td>Nama Dosen</td>
    <td>{{ matkul.nama_dosen }}</td>
  </tr>
  <tr>
    <td>Semester</td>
    <td>{{ matkul.semester_berapa }}</td>
  </tr>
  <tr>
    <td>Kelas</td>
    <td>{{ matkul.kelas }}</td>
  </tr>
  <tr>
    <td>Deskripsi</td>
    <td>{{ matkul.deskripsi }}</td>
  </tr>
</table>
 {% endblock content %}

story5/templates/story5/story5.html
{% extends 'base.html' %}
<!-- Block of Style-->
{% block style %}
<style>
  table,
  th,
  td {
    border: 1px black solid;
  }
  .kecilkan {
    height: 100em;
  }
</style>
{% endblock style %}
<!--Block of title-->
{% block title %}Story 5{% endblock title %}
<!-- Start of Content -->
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <!-- Form input-->
  {{ form.as_p }}
  <button class="btn" type="submit">Masukkan Data</button>
</form>

<h3>Mata Kuliah</h3>
<ul>
  {% for jadual in jadwal %}
    <li> <a href="{% url 'story5:detail' jadual.id %}">{{ jadual }}</a></li>
  {% endfor %}
</ul>

<!--End of Content-->
{% endblock content %}