cerita_billy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='index')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/',  include('story3.urls', namespace='story3')),
    path('story5/',  include('story5.urls', namespace='story5')),
    path('story6/',  include('story6.urls', namespace='story6')),
    path('story7/',  include('story7.urls', namespace='story7')),
    path('story8/',  include('story8.urls', namespace='story8')),
    path('story9/',  include('story9.urls', namespace='story9')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

story1/urls.py
from django.urls import path
from . import views

# Create your views here.


app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story3/urls.py
from django.urls import path
from . import views

# Create your views here.


app_name = 'story3'

urlpatterns = [
    path('', views.story3, name='story3'),
]

story5/urls.py
from django.urls import path
from . import views

# Create your views here.


app_name = 'story5'

urlpatterns = [
    path('', views.story5, name='story5'),
    path('<int:id>/', views.detail_matkul, name='detail'),
]

story6/urls.py
from django.urls import path
from . import views

# Create your views here.


app_name = 'story6'

urlpatterns = [
    path('', views.story6, name='story6'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'home/style/style.css' %}" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <!-- Block of Internal Style-->
    {% block style %} {% endblock style %}
    <title>{% block title %}<!-- Title goes here--> {% endblock %}</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar bg-dark navbar-expand-lg navbar-dark warna sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Story here
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'story1:story1' %}">Story 1</a></li>
                  <li><a class="dropdown-item" href="{% url 'story3:story3' %}">Story 3</a></li>
                  <li><a class="dropdown-item" href="{% url 'story5:story5' %}">Story 5</a></li>
                  <li><a class="dropdown-item" href="{% url 'story6:story6' %}">Story 6</a></li>
                  <li><a class="dropdown-item" href="{% url 'story7:story7' %}">Story 7</a></li>
                  <li><a class="dropdown-item" href="{% url 'story8:story8' %}">Story 8</a></li>
                  <li><a class="dropdown-item" href="{% url 'story9:story9' %}">Story 9</a></li>
              </ul>
            </li>
          </ul>
        </div>
          {% if user.is_authenticated %}

          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Halo {{ user }}</a></li>
            <li><a href="{% url 'story9:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Log Out</a></li>
          </ul>

          {% else %}

          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'story9:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="{% url 'story9:login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
          </ul>

          {% endif %}
      </div>
    </nav>
    <!-- End of Dropdown -->
    {% load crispy_forms_tags %}
    {% block content %} {% endblock %}

    <!-- footer -->
    <footer class="page-footer font-small warna pt-4 bg-dark">
      <div class="footer-copyright text-center py-3 text-light">
        © 2020 Billy Vande Yohannes
      </div>
    </footer>

    <!-- JavaScript siapatau butuh -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

templates/dasar.html
{% extends 'base.html' %}
<!-- Block of Style-->
{% block style %}
<!-- Apabila dibutuhkan Style internal dapat diissi disini-->
{% endblock style %}
<!--Block of title-->
{% block title %}<!-- Title tulis disini -->{% endblock title %}
<!-- Start of Content -->
{% block content %}
<!--End of Content-->
{% endblock content %}